echo "
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: init-argo-apps
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster
    repoURL: https://github.com/Robin1305/kubelab-incluster
    targetRevision: HEAD
  syncPolicy: {}
" > init.yaml
