apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubelab-application
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/kubelab-app
    repoURL: https://github.com/Robin1305/kubelab-incluster
    targetRevision: HEAD
  syncPolicy:
    automated: {}   
